name: run main.py

on:
  # Triggers the workflow every 0 am
  schedule:
    - cron: "0 0 1 1 *"
  push:

env:
    KEYFILE: ./creds.json
    STUDENTS: ./students.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: fetch student json data
        run: 'echo "$STUDENTS" > ./students.json'
        shell: bash
        env:
            STUDENTS : ${{ secrets.STUDENTS }}
            
                      
      - name: create credential key file
        run: 'echo "$KEYFILE" > ./creds.json'
        shell: bash
        env:
            KEYFILE : ${{ secrets.SOME_SECRET }}
            
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python ./src/main.py
        
      - name: remove student json key file
        run: 'rm ./students.json'
        shell: bash
        
      - name: remove credential key file
        run: 'rm ./creds.json'
        shell: bash
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
